### PR TITLE
Lesson 4.5: CSS Layout 

### PR DESCRIPTION
**Pull request by zeroban**
- Had trouble with the @media section not working. For some reason, VS Code kept giving me errors with my Live web server when I tested my page.

### CODE REVIEW

**Comment by Jkuffler** [comment]
Check out 
https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries 
There is helpful, basic examples for using media queries. Please bring up any specific questions in the Eridanus discussion channel - we'll be happy to help clear up blockers. This looks really good in a lot of ways; however, the assignment asks that the form element get some styling to it's display attribute which is currently missing from this pull request. 

I'm not sure what errors you are seeing. Currently on branch 4_5 my browser and IDE are not throwing errors.

**Comment by zeroban** [comment]
I looked over that help document you shared and it does provide some information however I am not seeing an answer as to why my window is not showing as responsive when I enter in a new parameter and save it the page takes on that new parameter and does not adjust if I change it so it does not meet it. I made a quick short video walking through this showing what I am running into. https://www.loom.com/share/53029fd9742d4d3588d3cd944bd7edbf

**Comment by Jkuffler** [comment]
Thanks for the video link! Have you tried targeting specific media or simply using `all` in your media query? Something like `@media all and (some condition)` then the changes you wish to apply for whatever condition: in this case screen resizing.

**Comment by zeroban** [comment]
I was able to do a new push with the correct information as needed. Let me know if I am able to go ahead and merge this pull or if you run into anything that needs to be corrected.

**Pull request merged**
